name: Build

on: [push, pull_request]

jobs:

  ## Build `temu` for Ubuntu
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install libcurl4-openssl-dev libssl-dev zlib1g-dev libsdl2-dev
      - run: make

  ## Build `js/riscvemu*` for WebAssembly
  build_js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install emscripten
      - run: make -f Makefile.js

  ## Build `temu` for macOS
  # build_mac:
  #     runs-on: macos-10.15
  #     env:
  #       DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
  #     steps:
  #       - uses: actions/checkout@v2
  #       - run: brew install openssl sdl2
  #       - run: make CFLAGS=-I$(brew --prefix)/opt/openssl/include LDFLAGS=-L$(brew --prefix)/opt/openssl/lib CONFIG_MACOS=y

  ## Build for iOS
  # build_ios:
  #     runs-on: macos-10.15
  #     env:
  #       DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
  #     steps:
  #       - uses: actions/checkout@v2
  #       - run: make CONFIG_IOS=y CONFIG_FS_NET= CONFIG_SDL=
  #       - run: make clean
  #       - run: make CONFIG_IOS_SIMULATOR=y CONFIG_FS_NET= CONFIG_SDL=
